apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: ignitelab-csuc-slackbot-lab3
    context: .
deploy:
  helm:
    releases:
    - name: ignitelab-csuc-slackbot-lab3
      chartPath: charts/ignitelab-csuc-slackbot
      values:
        image.repository: ignitelab-csuc-slackbot-lab3
