apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: ignitelab-csuc-slackbot-lab3
    context: .
deploy:
  helm:
    releases:
    - name: ignitelab-csuc-slackbot-lab3
      chartPath: charts/ignitelab-csuc-slackbot
      values:
        image.repository: ignitelab-csuc-slackbot-lab3
profiles:
- name: staging
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  patches:
  - op: add
    path: /deploy/helm/releases/0/setValueTemplates
    value: 
      ingress.enabled: true
      ingress.host: ignitelab-csuc-slackbot.{{.stagingDomain}}
