apiVersion: skaffold/v1beta14
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"  
  artifacts:
  - image: ignitelab-csuc-slackbot-lab3
    context: .
deploy:
  helm:
    releases:
    - name: ignitelab-csuc-slackbot-lab3
      chartPath: charts/ignitelab-csuc-slackbot
      values:
        image.repository: ignitelab-csuc-slackbot-lab3
profiles:
- name: staging
  patches:
  - op: add
    path: /deploy/helm/releases/0/values/ingress.enabled
    value: true
  - op: add
    path: /deploy/helm/releases/0/values/ingress.hosts.0.host
    value: ignitelab-csuc-slackbot.{{.stagingDomain}}
