{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ignitelab-csuc-slackbot
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.ingress.host }}
    port:
      name: http
      number: 3000
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ignitelab-csuc-slackbot
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - ignitelab-csuc-slackbot
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Values.ingress.host }}
        port:
          number: 3000
{{- end }}